server:
  servlet:
    context-path: /api
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ddshop
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
